name: Beta (TestFlight)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  beta:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install Tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist

      - name: Generate project
        run: tuist generate

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install fastlane
        run: gem install fastlane

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}

      - name: Prepare ASC key
        run: echo "${{ secrets.ASC_KEY_P8 }}" > AuthKey.p8

      - name: Fastlane beta
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        run: fastlane ios beta

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
