name: iOS CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install Tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist

      - name: Resolve Tuist dependencies
        run: tuist install

      - name: Generate project
        run: tuist generate

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            spm-${{ runner.os }}-

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: dd-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            dd-${{ runner.os }}-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install fastlane
        run: gem install fastlane

      - name: Tests
        run: fastlane ios test
